version: "3.9"  
services:

  splace_api:
    image: node:slim

    ports:
      - 8080:8080

    restart: always
    
    networks:
      - splace_bridge

    volumes:
      - ./:/usr/src/app

    command: sh -c "cd /usr/src/app && npm install && npm run start"

    environment:
      - DB_HOST=splace_db

    depends_on: [splace_db]

  splace_db: 
     image: mariadb:10.3

     restart: always 

     container_name: database 

     networks:
       - splace_bridge

     volumes:
       - splace_db_volume:/var/lib/mysql
       - ../splace-db/init/:/init 

     environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} 
       - MYSQL_DATABASE=${MYSQL_DATABASE}
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes: 
  splace_db_volume:

networks:
  splace_bridge:
